version: "3"
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: nodereact/server
    ports:
      - "8080:8080"
    env_file:
      - server-prod-variables.env
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: nodereact/client
    ports:
      - "5000:80"
