version: "3"
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: nodereact/server
    ports:
      - "8080:8080"
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: nodereact/client
    ports:
      - "4000:80"
